### ISSUE TITLE
OpenCV4Tegra dependency requirement?

### ISSUE THREAD

**Issue by kaisark** [jetsonhacks/installCaffeJTX1#7]
Is OpenCV4Tegra required if OpenCV3.3 has been installed on the TX1? I understand that having both  OpenCV4Tegra and OpenCV3.3 installed on the TX1 can cause some issues to surface. Some have advised removing OpenCV4Tegra from the TX1 to solve potential conflicts...

**Comment by jetsonhacks** [comment]
I'm not quite sure what you're asking. Neither are "required" unless you have programs which depend on them. I believe that some of the samples in the default JetPack installation may depend on OpenCV4Tegra, but you'd have to examine them on a case by case basis. 

Some people remove OpenCV4Tegra so that it's easier to keep the include paths and library paths straight. This avoids accidentally linking against the wrong library.

**Comment by kaisark** [comment]
I was just reading from the installCaffe.sh install script(see below). But, I see that OpenCV4Tegra sounds more like an application dependency than a Caffe TX1 build requirement. Cool. I uninstalled OpenCV4Tegra and kept OpenCV. The Caffe build went smoothly. I have built Caffe on the Raspberry Pi 3 in the past and it was a little grueling. Thanks again. I will close the issue.

# Prerequisites (which can be installed with JetPack 2):
# L4T 24.2 (Ubuntu 16.04)
# OpenCV4Tegra
# CUDA 8.0
# cuDNN v5.1
